### ISSUE TITLE
Not all boards are showing in dropdown

### ISSUE THREAD

**Issue by justs** [dospolov/trello-bookmark#1]
Really loved the previous extension. This extension is only showing about a fifth of my boards. Suspect it is a permissions issue as it looks like the only boards showing are public boards that I follow with only three of the boards being those that I created.

**Comment by dospolov** [comment]
@justs here you go:
![image](https://user-images.githubusercontent.com/670682/50785724-33930180-12ba-11e9-922c-0b711a548379.png)
just update plugin in settings

**Comment by justs** [comment]
I went to Chrome extension settings and updated and received an "updated" popup, but now I don't get any boards at all. 
![screenclip](https://user-images.githubusercontent.com/550659/50789133-ffe7b580-1280-11e9-9477-1dd36b6baf2c.png)
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by dospolov** [comment]
@justs remove plugin and install it again. If issue appears again please attach screenshot of opened developer tools (right click in popup -> inspect -> console)

**Comment by justs** [comment]
This is what I get in the console after uninstalling extension, quitting Chrome, restarting laptop, reinstalling extension.
`App.js:101 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at App.js:101
    at Array.filter (<anonymous>)
    at App.js:101
    at Array.map (<anonymous>)
    at App.js:99`

![image 2019-01-07 at 2 24 38 pm](https://user-images.githubusercontent.com/550659/50791703-3ecd3980-1288-11e9-9894-f3ffbcad5916.png)

**Comment by dospolov** [comment]
I'm not able to reproduce. Would you like to have skype screen sharing session?

**Comment by justs** [comment]
Certainly, if that works for you. My skype is justin.sturgis
I also have Jitsi, Appear.in, Daily.co, or TeamViewer.

**Comment by dospolov** [comment]
great, lets try TeamViewer

**Comment by iltrico** [comment]
I have the exact same issue as @justs, removed the extension, re-installed, cleared the permissions on trello, reinstalled but it's still not working.

Here's the output from the console
![schermata 2019-01-25 alle 10 40 33](https://user-images.githubusercontent.com/30796609/51738019-6bf25800-208e-11e9-8765-b1c728e22bdb.png)

Did you find a solution?

**Comment by dospolov** [comment]
@iltrico we've managed to find the solution for @justs 
but I see you have another error. 
I'm not able to reproduce it on my end. We can try to have a skype call for that. My SkypeID: live:dospolov

**Comment by dospolov** [comment]
@iltrico seems I found the bug. Just published a new version to chrome store (v.1.11.0).
Please reinstall plugin again

**Comment by iltrico** [comment]
👍 now it works! Thank you for your great work
