### ISSUE TITLE
[bug] blank window after list selection

### ISSUE THREAD

**Issue by alexriabtsev** [dospolov/trello-bookmark#3]
Pre-requisites:
- Brave browser

Steps to reproduce:
- open Trello Bookmark
- choose Board and list
- get blank window (no Save button)

<img width="1440" alt="Screen Shot 2019-04-18 at 20 25 58" src="https://user-images.githubusercontent.com/8425396/56379401-59fcfd00-6218-11e9-8adc-4a514315e448.png">
<img width="1440" alt="Screen Shot 2019-04-18 at 20 25 34" src="https://user-images.githubusercontent.com/8425396/56379403-59fcfd00-6218-11e9-90b4-d481c36f0f30.png">
<img width="1440" alt="Screen Shot 2019-04-18 at 20 24 58" src="https://user-images.githubusercontent.com/8425396/56379404-5a959380-6218-11e9-91e4-99871a3bb291.png">

**Comment by dospolov** [comment]
hi @alexriabtsev 
that might be some specific issue in Brave Browser, but let's try to figure out.
1. Have you selected the list? (it's not visible on your screenshots)
2. Can you try another paths? (teams, boards, lists)
3. Please reinstall the plugin
4. Could you show the console of the plugin?

**Comment by alexriabtsev** [comment]
hi @dospolov 
1. yes
2. yes, same result
3. will do today and post and update
4. you mean Chrome DevTools?

**Comment by alexriabtsev** [comment]
OK. I narrowed the bug. It exists ONLY when I select **Private** boards.
Teams boards/lists work perfect.

**Comment by dospolov** [comment]
@alexriabtsev I'm not able to investigate with your info.
But you can ping me at Skype: live:dospolov, 
and we will figure out something

**Comment by Kmfernan5** [comment]
Same problem here. Making it public didn’t fix it.
